<!DOCTYPE html>
<html class="whois">
<head>
<title>Penny Juice</title>
<link rel="stylesheet" type="text/css" href="index.css"/>
</head>
<body>
<img src="whois.jpg" alt="Who is Penny Juice?"/>
<dl>
<dt>People have alot to say about Penny Juice!</dt>
<dd class="pink">
THE CHILDREN AT KID KOLLEGE LOVE THE TASTE OF PENNY JUICE AND DRINK IT WITHOUT
ENCOURAGEMENT FROM OUR TEACHERS. I LIKE PENNY JUICE FOR THAT REASON AND BECAUSE
IT IS 100% JUICE FROM CONCENTRATE REQUIRING NO REFRIGERATION PRIOR TO MIXING.
THE HANDY MIX PITCHER TAKE THE GUESS WORK OUT OF PREPARATION.

<cite>CASSIE PENCE - KID KOLLEGE/BILLINGS, MT</cite>
</dd>
<dd class="blue">
“THANK YOU FOR THE OPPORTUNITY TO LET EVERYONE KNOW ABOUT YOUR TERRIFIC
COMPANY! IT’S EASY TO STORE AND MIX AND WE RECEIVE GREAT SERVICE!”

<cite>
MARY CELLA - BLISS ACADEMY EARLY LEARNING CENTER/GREENWOOD VILLAGE, CO
</cite>
</dd>
<dd class="green">
I LOVE THE PROMPTNESS OF SERVICE! “EASY MIXING BOY”

<cite>KID'S WORLD LEARNING CENTER/ BROOKINGS, SD</cite>
</dd>
<dd>
I HAVE BEEN USING PENNY JUICE AT MY CHILDCARE CENTER FOR 2 YEARS. THE CHILDREN
LOVE ALL THE FUN COLORS. I HAVE RECOMMENDED PENNY JUICE TO OTHER CHILDCARE
DIRECTORS IN THE AREA.
<cite>
DANA HOENIGSCHMIDT - KIDS COUNTRY CHILDCARE/ST. FRANCIS, MN
</cite>
</dd>
</dl>
<nav>Who is Penny Juice? / What is Penny Juice? / Where is Penny Juice?</nav>
<nav>Got Juice? / E-mail / HOME</nav>
</body>
</html>


