#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#define true 1
#define false 0

/*
#1 If we list all the natural numbers below 10 that are multiples of 3 or 5,
we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

Antwoord: 233,168
*/

static uint8_t decimals32(uint32_t n)
{
    uint8_t i = 0;
    while (n) n = n / 10, i++;
    return i;
}

static uint8_t decimals64(uint64_t n)
{   uint8_t i = 0;
    while (n) n = n / 10, i++;
    return i;
}

static void xstring32(char *s, uint32_t n)
{
    uint8_t decs = decimals32(n);
    s[decs] = 0;
    while (n)
    {
        s[--decs] = n % 10 + '0';
        n = n / 10;
    }
}

static void xstring64(char *s, uint64_t n)
{
    uint8_t decs = decimals64(n);
    s[decs] = 0;
    while (n)
    {
        s[--decs] = n % 10 + '0';
        n = n / 10;
    }
}

static const uint32_t summation1(uint32_t n, uint32_t xmax)
{   uint32_t xlen = xmax / n;
    return ((xlen * (xlen + 1)) >> 1) * n;
}

static uint32_t multiples1(uint32_t limit)
{   return summation1(3, limit - 1) + summation1(5, limit - 1) - summation1(15, limit - 1);
}

static char *problem1()
{
    char *ret = malloc(50);
    xstring32(ret, multiples1(1000));
    return ret;
}

/*
#2 Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.

Antwoord: 4,613,732
*/

static uint32_t fibonacci(uint32_t xmax)
{
    uint32_t term1 = 1, term2 = 2, temp = 0, xsum = 2;
    while (true)
    {   temp = term1 + term2;
        if (temp > xmax) break;
        if (temp % 2 == 0) xsum += temp;
        term1 = term2, term2 = temp;
    }
    return xsum;
}

static char *problem2()
{
    char *ret = malloc(50);
    xstring32(ret, fibonacci(4000000));
    return ret;
}

/*
#3 The prime factors of 13195 are 5, 7, 13 and 29.
What is the largest prime factor of the number 600,851,475,143?

Antwoord: 6,857
*/

/*
71 * 839 * 1471 * 6857 = 600851475143
*/

static int isPrime(uint32_t n)
{
    uint32_t i;
    for (i = 2; i < n; i++)
        if (n % i == 0) return 0;
    return 1;
}

static char *problem3()
{
    uint64_t n = 600851475143ULL;
    uint32_t best = 0;
    while (n > 1)
    {
        uint32_t i;
        uint32_t factor = 0;
        for (i = 2; i < 999999; i++)
        {
            if (isPrime(i) == 0) continue;
            if (n % i == 0)
            {   factor = i;
                break;
            }
        }
        if (factor > best) best = factor;
        n = n / factor;
    }
    char *ret = malloc(50);
    xstring32(ret, best);
    return ret;
}

/*
#4 A palindromic number reads the same both ways. The largest palindrome
made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

Antwoord: 906,609
*/

static uint32_t reverse32(uint32_t n, uint8_t base)
{   uint32_t rev = 0, temp = 0;
    for (temp = n; temp != 0; temp /= base) rev = rev * base + temp % base;
    return rev;
}

static int ispalindrome32(uint32_t n, uint8_t base)
{   return n == reverse32(n, base);
}

static char *problem4()
{   uint32_t best = 0;
    uint32_t a, b, c;
    for (a = 0; a < 1000; a++)
    {   for (b = 0; b < 1000; b++)
        {   c = a * b;
            if (ispalindrome32(c, 10) && c > best)
                best = c;
        }
    }
    char *ret = malloc(50);
    xstring32(ret, best);
    return ret;
}

/*
#5 2520 is the smallest number that can be divided by
each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly
divisible by all of the numbers from 1 to 20?

Antwoord: 232,792,560
*/

static int isdivisible(uint32_t n, uint32_t lower, uint32_t max)
{
    uint32_t i;
    for (i = lower; i <= max; i++) if (n % i > 0) return false;
    return true;
}

static char *problem5()
{
    uint32_t lower = 11, max = 20;
    uint32_t start = 2520, number = start;
    while (isdivisible(number, lower, max) == false) number += start;
    char *ret = malloc(50);
    xstring32(ret, number);
    return ret;
}

/*
#6 The sum of the squares of the first ten natural numbers is,
1^2 + 2^2 + ... + 10^2 = 385

The square of the sum of the first ten natural numbers is,
(1 + 2 + ... + 10)2 = 552 = 3025

Hence the difference between the sum of the squares of the first ten
natural numbers and the square of the sum is 3025 − 385 = 2640.

Find the difference between the sum of the squares of the
first one hundred natural numbers and the square of the sum.

Antwoord: 25,164,150
*/

static char *problem6()
{
    uint32_t min = 1, max = 100;
    uint32_t sumsquare = 0, squaresum = 0;
    uint32_t i;
    for (i = min; i <= max; i++) sumsquare += i * i;
    for (i = min; i <= max; i++) squaresum += i;
    squaresum = squaresum * squaresum;
    char *ret = malloc(50);
    xstring32(ret, squaresum - sumsquare);
    return ret;
}

/*
#7 By listing the first six prime numbers: 2, 3, 5,
7, 11, and 13, we can see that the 6th prime is 13.

What is the 10 001st prime number?

Antwoord: 104,743
*/

static uint32_t reducer7(uint32_t n)
{   if (n > 300 * 300) return n / 300;
    if (n > 100 * 100) return n / 100;
    if (n > 8 * 8) return n / 8;
    return n;
}

static char *problem7()
{
    uint32_t n = 10001;
    uint32_t p = 3, sqp = reducer7(p), ret = 0;
    uint32_t i, j;
    for (j = 0; j < n - 1; j++)
    {   for (i = 2; i < sqp; i++)
            if (p % i == 0) sqp = reducer7(++p), i = 1;
        ret = p, p += 2, sqp = reducer7(p);
    }
    char *ret2 = malloc(50);
    xstring32(ret2, ret);
    return ret2;
}

/*
#8 Largest product in a series

The four adjacent digits in the 1000-digit number that
have the greatest product are 9 × 9 × 8 × 9 = 5832.

Find the thirteen adjacent digits in the 1000-digit number that
have the greatest product. What is the value of this product?

Antwoord: 23,514,624,000
*/

static char series1[] = "73167176531330624919225119674426574742355349194934"
        "96983520312774506326239578318016984801869478851843"
        "85861560789112949495459501737958331952853208805511"
        "12540698747158523863050715693290963295227443043557"
        "66896648950445244523161731856403098711121722383113"
        "62229893423380308135336276614282806444486645238749"
        "30358907296290491560440772390713810515859307960866"
        "70172427121883998797908792274921901699720888093776"
        "65727333001053367881220235421809751254540594752243"
        "52584907711670556013604839586446706324415722155397"
        "53697817977846174064955149290862569321978468622482"
        "83972241375657056057490261407972968652414535100474"
        "82166370484403199890008895243450658541227588666881"
        "16427171479924442928230863465674813919123162824586"
        "17866458359124566529476545682848912883142607690042"
        "24219022671055626321111109370544217506941658960408"
        "07198403850962455444362981230987879927244284909188"
        "84580156166097919133875499200524063689912560717606"
        "05886116467109405077541002256983155200055935729725"
        "71636269561882670428252483600823257530420752963450";

static char *problem8()
{
    char *s = series1;
    uint64_t cur = 0, best = 0;
    while (*s)
    {   cur = (cur % 1000000000000ULL) * 10 + (*s++ - '0');
        uint64_t peel = cur, product = 1;
        while (peel) product *= peel % 10, peel = peel / 10;
        if (product > best) best = product;
    }
    char *ret = malloc(50);
    xstring64(ret, best);
    return ret;
}

/*
#9 Special Pythagorean triplet

A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,
a2 + b2 = c2

For example, 3^2 + 4^2 = 9 + 16 = 25 = 5^2.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

Antwoord: 31,875,000
*/

static uint32_t problem9x()
{
    uint32_t search = 1000;
    uint32_t a, b;
    for (a = 1; a <= search - 2; a++)
    {   for (b = 1; b <= search - 2; b++)
        {   uint32_t c = search - a - b;
            if (a * a + b * b == c * c)
                return a * b * c;
        }
    }
    return 0;
}

static char *problem9()
{
    char *ret = malloc(50);
    xstring32(ret, problem9x());
    return ret;
}

/*
#10 Summation of primes

The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million.

Antwoord: 142,913,828,922
*/

#define LIMIT10 2000000

static char *problem10()
{
    uint8_t *v = malloc(LIMIT10 + 1);
    uint32_t i, j;
    for (i = 0; i < LIMIT10; i++)
        v[i] = 1;
    v[0] = v[1] = 0;
    for (i = 2; i * i < LIMIT10; i++)
        if (v[i] == 1)
            for (j = i * 2; j <= LIMIT10; j += i)
                v[j] = 0;
    uint64_t sum = 0;
    for (i = 0; i < LIMIT10; i++)
        sum += v[i] == 1 ? i : 0;
    free(v);
    char *ret = malloc(50);
    xstring64(ret, sum);
    return ret;
}

/*
#11 Largest product in a grid

In the 20×20 grid below, four numbers along
a diagonal line have been marked in red.

08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48

The product of these numbers is 26 × 63 × 78 × 14 = 1788696.

What is the greatest product of four adjacent numbers in the same
direction (up, down, left, right, or diagonally) in the 20×20 grid?

Antwoord: 70,600,674
*/

uint8_t t11[20][20] = {{ 8, 2,22,97,38,15, 0,40, 0,75, 4, 5, 7,78,52,12,50,77,91, 8},
            {49,49,99,40,17,81,18,57,60,87,17,40,98,43,69,48, 4,56,62, 0},
            {81,49,31,73,55,79,14,29,93,71,40,67,53,88,30, 3,49,13,36,65},
            {52,70,95,23, 4,60,11,42,69,24,68,56, 1,32,56,71,37, 2,36,91},
            {22,31,16,71,51,67,63,89,41,92,36,54,22,40,40,28,66,33,13,80},
            {24,47,32,60,99, 3,45, 2,44,75,33,53,78,36,84,20,35,17,12,50},
            {32,98,81,28,64,23,67,10,26,38,40,67,59,54,70,66,18,38,64,70},
            {67,26,20,68, 2,62,12,20,95,63,94,39,63, 8,40,91,66,49,94,21},
            {24,55,58, 5,66,73,99,26,97,17,78,78,96,83,14,88,34,89,63,72},
            {21,36,23, 9,75, 0,76,44,20,45,35,14, 0,61,33,97,34,31,33,95},
            {78,17,53,28,22,75,31,67,15,94, 3,80, 4,62,16,14, 9,53,56,92},
            {16,39, 5,42,96,35,31,47,55,58,88,24, 0,17,54,24,36,29,85,57},
            {86,56, 0,48,35,71,89, 7, 5,44,44,37,44,60,21,58,51,54,17,58},
            {19,80,81,68, 5,94,47,69,28,73,92,13,86,52,17,77, 4,89,55,40},
            { 4,52, 8,83,97,35,99,16, 7,97,57,32,16,26,26,79,33,27,98,66},
            {88,36,68,87,57,62,20,72, 3,46,33,67,46,55,12,32,63,93,53,69},
            { 4,42,16,73,38,25,39,11,24,94,72,18, 8,46,29,32,40,62,76,36},
            {20,69,36,41,72,30,23,88,34,62,99,69,82,67,59,85,74, 4,36,16},
            {20,73,35,29,78,31,90, 1,74,31,49,71,48,86,81,16,23,57, 5,54},
            { 1,70,54,71,83,51,54,69,16,92,33,48,61,43,52, 1,89,19,67,48}};

static char *problem11()
{   uint32_t best = 0;
    uint8_t i, j;
    for (i = 0; i < 20; i++)
    {   for (j = 0; j < 16; j++)
        {   uint32_t prod = t11[i][j] * t11[i][j+1] * t11[i][j+2] * t11[i][j+3];
            if (prod > best) best = prod;
            prod = t11[j][i] * t11[j+1][i] * t11[j+2][i] * t11[j+3][i];
            if (prod > best) best = prod;
        }
    }
    for (i = 0; i < 16; i++)
    {   for (j = 0; j < 16; j++)
        {   uint32_t prod = t11[i][j] * t11[i+1][j+1] * t11[i+2][j+2] * t11[i+3][j+3];
            if (prod > best) best = prod;
        }
    }
    for (i = 3; i < 20; i++)
    {   for (j = 0; j < 16; j++)
        {   uint32_t prod = t11[i][j] * t11[i-1][j+1] * t11[i-2][j+2] * t11[i-3][j+3];
            if (prod > best) best = prod;
        }
    }
    char *ret = malloc(50);
    xstring32(ret, best);
    return ret;
}

/*
#12 Highly divisible triangular number

The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The
first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

Antwoord: 76,576,500
*/

static uint32_t num_divisors(uint32_t n)
{   if (n % 2 == 0) n = n >> 1;
    uint32_t divisors = 1, count = 0;
    while (n % 2 == 0) count++, n = n >> 1;
    divisors = divisors * (count + 1);
    uint32_t p = 3;
    while (n != 1)
    {   count = 0;
        while (n % p == 0) count++, n = n / p;
        divisors = divisors * (count + 1), p += 2;
    }
    return divisors;
}

static uint32_t find_triangular_index(uint16_t factor_limit)
{   uint32_t n = 1, lnum = num_divisors(n), rnum = num_divisors(n + 1);
    while (lnum * rnum < factor_limit)
        lnum = rnum, rnum = num_divisors(++n + 1);
    return n;
}

static char *problem12()
{   uint32_t i = find_triangular_index(500);
    uint32_t ret = ((i * (i + 1)) >> 1);
    char *ret2 = malloc(50);
    xstring32(ret2, ret);
    return ret2;
}

/*
#13 Large sum

Work out the first ten digits of the sum of the following one-hundred 50-digit numbers.

Antwoord: 5,537,376,230
*/

static char *problem13()
{
    uint8_t numbers[5000];
    FILE *fp = fopen("euler13.txt", "r");
    uint16_t i = 0, j;
    while (i < 5000)
    {
        int c = fgetc(fp);
        if (isdigit(c))
            numbers[i++] = c - '0';
    }
    fclose(fp);
    uint8_t totalSum[100];
    uint64_t sum = 0;
    uint8_t end = 0;
    for (i = 50; i > 0; i--)
    {
        for (j = 0; j < 100; j++)
            sum += numbers[j * 50 + (i - 1)];
        totalSum[end++] = sum % 10;
        sum /= 10;
    }
    for (;sum > 0; sum /= 10)
        totalSum[end++] = sum % 10;
    end--;
    char *ret = malloc(50);
    for (i = 0; i < 10; i++)
        ret[i] = (char)(totalSum[end--] + 48);
    ret[i] = 0;
    return ret;
}

/*
#14 Longest Collatz sequence

The following iterative sequence is defined for the set of positive integers:

n -> n/2 (n is even)
n -> 3n + 1 (n is odd)

Using the rule above and starting with 13, we generate the following sequence:
13 -> 40 -> 20 -> 10 -> 5 -> 16 -> 8 -> 4 -> 2 -> 1

It can be seen that this sequence (starting at 13 and finishing at 1)
contains 10 terms. Although it has not been proved yet (Collatz Problem),
it is thought that all starting numbers finish at 1.

Which starting number, under one million, produces the longest chain?

NOTE: Once the chain starts the terms are allowed to go above one million.

Antwoord: 837,799
*/

static uint32_t collatz(uint32_t n)
{   uint32_t count = 1;
    while (n > 1) n = n % 2 == 0 ? n >> 1 : n * 3 + 1, count++;
    return count;
}

static char *problem14()
{
    uint32_t lower = 1, upper = 1000000;
    uint32_t best_start = 0, best_length = 0;
    uint32_t i;
    for (i = lower; i < upper; i++)
    {   uint32_t length = collatz(i);
        if (length > best_length)
            best_start = i, best_length = length;
    }
    char *ret = malloc(50);
    xstring32(ret, best_start);
    return ret;
}

/*
#15 Lattice paths

Starting in the top left corner of a 2x2 grid, and only being able to move
to the right and down, there are exactly 6 routes to the bottom right corner.

How many such routes are there through a 20×20 grid?

Antwoord: 137,846,528,820
*/

static char *problem15()
{
    uint8_t size = 20;
    uint64_t paths = 1;
    uint8_t i;
    for (i = 0; i < size; i++)
        paths = (paths * (2 * size - i)) / (i + 1);
    char *ret = malloc(50);
    xstring64(ret, paths);
    return ret;
}

/*
#16 Power digit sum

2^15 = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.

What is the sum of the digits of the number 2^1000?

Antwoord: 1,366
*/

static char *problem16()
{
    uint16_t e = 1000;
    uint8_t largeNum[400];
    memset(largeNum, 0, 400);
    largeNum[0] = 2;
    uint8_t carry = 0;
    uint32_t sum = 0;
    uint16_t i;
    while (--e)
    {   for (i = 0; i < sizeof(largeNum); i++)
        {   largeNum[i] *= 2;
            largeNum[i] += carry;
            carry = largeNum[i] / 10;
            largeNum[i] = largeNum[i] % 10;
        }
    }
    for (i = 0; i < sizeof(largeNum); i++)
        sum += largeNum[i];
    char *ret = malloc(50);
    xstring32(ret, sum);
    return ret;
}

/*
#17 Number letter counts

If the numbers 1 to 5 are written out in words: one, two, three, four,
five, then there are 3 + 3 + 5 + 4 + 4 = 19 letters used in total.

If all the numbers from 1 to 1000 (one thousand) inclusive
were written out in words, how many letters would be used?

NOTE: Do not count spaces or hyphens. For example, 342 (three hundred and
forty-two) contains 23 letters and 115 (one hundred and fifteen) contains
20 letters. The use of "and" when writing out numbers is in compliance
with British usage.

Antwoord: 21,124
*/

static size_t len(const char *s)
{
    return strlen(s);
}

static char *problem17()
{   char arr1[][15] = {"one", "two", "three", "four", "five", "six", "seven", "eight", "nine",
        "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen",
        "seventeen", "eighteen", "nineteen",
        "twenty", "thirty", "forty", "fifty", "sixty",
        "seventy", "eighty", "ninety"};
    uint32_t xsum = 0;
    uint8_t i, j;
    for (i = 0; i < 19; i++)
        xsum += len(arr1[i]);
    for (i = 19; i < 27; i++)
    {   xsum += len(arr1[i]);
        for (j = 0; j < 9; j++)
            xsum += len(arr1[i]) + len(arr1[j]);
    }
    for (i = 0; i < 9; i++)
    {   xsum += len(arr1[i]) + len("hundred");
        for (j = 0; j < 19; j++)
            xsum += len(arr1[i]) + len("hundred") + len("and") + len(arr1[j]);
        for (j = 19; j < 27; j++)
        {   xsum += len(arr1[i]) + len("hundred") + len("and") + len(arr1[j]);
            uint8_t k;
            for (k = 0; k < 9; k++)
                xsum += len(arr1[i]) + len("hundredand") + len(arr1[j]) + len(arr1[k]);
        }
    }
    xsum += len("onethousand");
    char *ret = malloc(50);
    xstring32(ret, xsum);
    return ret;
}

/*
#18: Maximum path sum I

By starting at the top of the triangle below and moving to adjacent
numbers on the row below, the maximum total from top to bottom is 23.

3
7 4
2 4 6
8 5 9 3

That is, 3 + 7 + 4 + 9 = 23.

Find the maximum total from top to bottom of the triangle below:

75
95 64
17 47 82
18 35 87 10
20 04 82 47 65
19 01 23 75 03 34
88 02 77 73 07 63 67
99 65 04 28 06 16 70 92
41 41 26 56 83 40 80 70 33
41 48 72 33 47 32 37 16 94 29
53 71 44 65 25 43 91 52 97 51 14
70 11 33 28 77 73 17 78 39 68 17 57
91 71 52 38 17 14 91 43 58 50 27 29 48
63 66 04 68 89 53 67 30 73 16 69 87 40 31
04 62 98 27 23 09 70 98 73 93 38 53 60 04 23

NOTE: As there are only 16384 routes, it is possible to solve this
problem by trying every route. However, Problem 67, is the same
challenge with a triangle containing one-hundred rows; it cannot be
solved by brute force, and requires a clever method! ;o)

Antwoord: 1,074
*/

static uint64_t myPow64(uint64_t base, uint64_t e)
{
    if (e == 0) return 1;
    uint64_t ret = base;
    while (--e) ret *= base;
    return ret;
}

#if 0
static uint8_t triangle[][4] = {
    {3,0,0,0},
    {7,4,0,0},
    {2,4,6,0},
    {8,5,9,3}};
#else
static uint8_t triangle[][15] = {
    {75, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {95,64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {17,47,82, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {18,35,87,10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {20, 4,82,47,65, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {19, 1,23,75, 3,34, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {88, 2,77,73, 7,63,67, 0, 0, 0, 0, 0, 0, 0, 0},
    {99,65, 4,28, 6,16,70,92, 0, 0, 0, 0, 0, 0, 0},
    {41,41,26,56,83,40,80,70,33, 0, 0, 0, 0, 0, 0},
    {41,48,72,33,47,32,37,16,94,29, 0, 0, 0, 0, 0},
    {53,71,44,65,25,43,91,52,97,51,14, 0, 0, 0, 0},
    {70,11,33,28,77,73,17,78,39,68,17,57, 0, 0, 0},
    {91,71,52,38,17,14,91,43,58,50,27,29,48, 0, 0}, 
    {63,66, 4,68,89,53,67,30,73,16,69,87,40,31, 0},
    { 4,62,98,27,23, 9,70,98,73,93,38,53,60, 4,23}};
#endif

static char *problem18()
{   uint32_t possibilities = myPow64(2, sizeof(triangle[0]) - 1);
    uint32_t best = 0;
    uint32_t i, j;
    for (i = 0; i <= possibilities; i++)
    {   uint32_t index = 0;
        uint32_t sum = triangle[0][0];
        for (j = 0; j < sizeof(triangle[0]) - 1; j++)
        {   index = index + (i >> j & 1);
            uint8_t value = triangle[j + 1][index];
            sum += value;
        }
        if (sum > best) best = sum;
    }
    char *ret = malloc(50);
    xstring32(ret, best);
    return ret;
}

static char answers2[][50] = {"233168", "4613732", "6857",
    "906609", "232792560", "25164150", "104743", "23514624000",
    "31875000", "142913828922", "70600674", "76576500", "5537376230", "837799", "137846528820",
    "1366", "21124", "1074", "171", "648", "31626", "871198282",
    "4179871", "2783915460", "4782", "983", "-59231",
    "669171001", "9183", "443839", "73682", "45228", "100", "40730", "55", "872187", "748317",
    "932718654", "840", "210", "7652413", "162", "16695334890", "5482660", "1533776805", "5777",
    "134043", "9110846700", "296962999629", "997651",
    "121313", "142857", "4075", "376", "249", "972", "153", "26241", "0", "0", "0",
    "127035954683"};

static char *run(uint32_t p)
{
    switch (p)
    {
    case 1: return problem1();
    case 2: return problem2();
    case 3: return problem3();
    case 4: return problem4();
    case 5: return problem5();
    case 6: return problem6();
    case 7: return problem7();
    case 8: return problem8();
    case 9: return problem9();
    case 10: return problem10();
    case 11: return problem11();
    case 12: return problem12();
    case 13: return problem13();
    case 14: return problem14();
    case 15: return problem15();
    case 16: return problem16();
    case 17: return problem17();
    case 18: return problem18();
    }
    return 0;
}

static void runjob(uint32_t p)
{
    char *answer = run(p);
    if (strcmp(answer, answers2[p - 1]) != 0)
        printf("error!");
    printf("#%u: %s\r\n", p, answer);
    free(answer);
}

int main()
{
    uint8_t i;
    for (i = 1; i <= 18; i++)
        runjob(i);
    return 0;
}

