<!DOCTYPE html>

<?php
echo file_get_contents("achtung.html");
?>

<html>
<head>
<title>Project Euler</title>
<link rel="stylesheet" type="text/css" href="common.css"/>
<style>
code, kbd, samp {
    white-space: pre;
}

var {
    font-family: monospace;
    font-style: normal;
}

samp {
    color: gray;
}

code em {
    font-style: normal;
    color: red;
}
</style>
</head>
<body>
<?php
require_once("mainmenu.php");
$mm = new MainMenu();
echo $mm;
?>

<main style="width: 900px;">
<h1>Project Euler</h1>
<h2>#1: Multiples of 3 and 5</h2>
<p>
If we list all the natural numbers below 10 that are multiples
of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
</p>
<p>
Find the sum of all the multiples of 3 or 5 below 1000.
</p>
<code>
limit = 1000, xsum = 0;
for (x = 1; x &lt; limit; x++)
    if (x % 3 == 0 || x % 5 == 0)
        xsum += x;
alert(xsum);    // should give 233,168
</code>

<h2>#2: Even Fibonacci numbers</h2>
<p>
Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:
</p>
<p>
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
</p>
<p>
By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.
</p>
<code>
xmax = 4000000, term1 = 1, term2 = 2, temp = 0, xsum = 0;

if (term1 % 2 == 0)
    xsum += term1

if (term2 % 2 == 0)
    xsum += term2

while ((temp = term1 + term2) &lt;= xmax)
{
    if (temp % 2 == 0)
        xsum += temp;
    
    term1 = term2;
    term2 = temp;
}

alert(xsum);    // should give 4,613,732
</code>

</main>
</body>
</html>



