package main

import "fmt"

/*
#1 If we list all the natural numbers below 10 that are multiples of 3 or 5,
we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

Antwoord: 233,168
*/

func problem1() string {
    var sum int32 = 0
    for i := int32(0); i < 1000; i++ {
        if i % 3 == 0 || i % 5 == 0 { sum += i }
    }
    var ret string = fmt.Sprintf("%d", sum);
    return ret
}

/*
#2 Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.

Antwoord: 4,613,732
*/

func problem2() string {
    var xmax, term1, term2, temp, xsum int32 = 4000000, 1, 2, 0, 2

    for {
        temp = term1 + term2
        if temp > xmax { break }
        if temp % 2 == 0 { xsum += temp }
        term1 = term2
        term2 = temp
    }
    return fmt.Sprintf("%d", xsum)
}

/*
#3 The prime factors of 13195 are 5, 7, 13 and 29.
What is the largest prime factor of the number 600,851,475,143?

Antwoord: 6,857
*/

func primeHelper(n int64) int64 {
    var presets = [4]int64{3000,300,100,8}
    for i := 0; i < 4; i++ {
        if n > presets[i] * presets[i] { return n / presets[i] }
    }
    return 0
}

func isprime(n int64) bool {
    if n == 0 || n == 1 { return false }
    var limit = primeHelper(n)
    for i := int64(2); i < limit; i++ {
        if n % i == 0 { return false }
    }
    return true
}

func problem3() string {
    var n int64 = 600851475143
    var best int64 = 0
    for n > 1 {
        var factor int64 = 0
        for i := int64(2); i < 999999; i++ {
            if isprime(i) == false { continue }
            if n % i == 0 {
                factor = i
                break
            }
        }
        if factor > best { best = factor }
        n = n / factor
    }
    var ret string = fmt.Sprintf("%d", best)
    return ret
}

/*
#4 A palindromic number reads the same both ways. The largest palindrome
made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

Antwoord: 906,609
*/

func isPalindrome(n int) bool {
    var temp, rev = n, 0
    for temp != 0 {
        rev = rev * 10 + temp % 10
        temp = temp / 10
    }
    return n == rev
}

func problem4() string {
    var best = 0
    for a := 100; a < 1000; a++ {
        for b := 100; b < 1000; b++ {
            var c = a * b
            if isPalindrome(c) && c > best { best = c }
        }
    }
    var ret string = fmt.Sprintf("%d", best)
    return ret
}

/*
#5 2520 is the smallest number that can be divided by
each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly
divisible by all of the numbers from 1 to 20?

Antwoord: 232,792,560
*/

func isdivisible(n int, lower int, max int) bool {
    for i := lower; i <= max; i++ {
        if n % i > 0 { return false }
    }
    return true
}

func problem5() string {
    var start = 2560
    var number = start
    for isdivisible(number, 11, 20) == false { number += start }
    return fmt.Sprintf("%d", number)
}

/*
#6 The sum of the squares of the first ten natural numbers is,
1^2 + 2^2 + ... + 10^2 = 385

The square of the sum of the first ten natural numbers is,
(1 + 2 + ... + 10)2 = 552 = 3025

Hence the difference between the sum of the squares of the first ten
natural numbers and the square of the sum is 3025 − 385 = 2640.

Find the difference between the sum of the squares of the
first one hundred natural numbers and the square of the sum.

Antwoord: 25,164,150
*/

func problem6() string {
    var sumsquare, squaresum = 0, 0
    for x := 1; x <= 100; x++ {
        sumsquare += x * x
        squaresum += x
    }
    var ret string = fmt.Sprintf("%d", squaresum * squaresum - sumsquare)
    return ret
}

/*
#7 By listing the first six prime numbers: 2, 3, 5,
7, 11, and 13, we can see that the 6th prime is 13.

What is the 10 001st prime number?

Antwoord: 104,743
*/

func reducer7(n int) int {
    if n > 300 * 300 { return n / 300 }
    if n > 100 * 100 { return n / 100 }
    if n > 8 * 8 { return (n / 8) }
    return n
}

func problem7() string {
    var p = 3
    var sqp = reducer7(p)
    var ret = 0
    var n = 10001
    for j := 0; j < n - 1; j++ {
        for i := 2; i < sqp; i++ {
            if p % i == 0 {
                p += 1
                sqp = reducer7(p)
                i = 1
            }
        }
        ret = p
        p += 2
        sqp = reducer7(p)
    }
    return fmt.Sprintf("%d", ret)
}

/*
#8 Largest product in a series

The four adjacent digits in the 1000-digit number that
have the greatest product are 9 × 9 × 8 × 9 = 5832.

Find the thirteen adjacent digits in the 1000-digit number that
have the greatest product. What is the value of this product?

Antwoord: 23,514,624,000
*/

/*  
#9 Special Pythagorean triplet

A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,
a2 + b2 = c2

For example, 3^2 + 4^2 = 9 + 16 = 25 = 5^2.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

Antwoord: 31,875,000
*/

func problem9x() int {
    for a := 1; a < 1000 - 1; a++ {
        for b := 1; b < 1000 - a; b++ {
            var c = 1000 - a - b
            if a * a + b * b == c * c {
                return a * b * c
            }
        }
    }
    return 0
}

func problem9() string {
    return fmt.Sprintf("%d", problem9x())
}

/*
#10 Summation of primes

The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million.

Antwoord: 142,913,828,922
*/

func problem10() string {
    var v [2000000]bool
    for i := 0; i < 2000000; i++ { v[i] = true }
    v[0], v[1] = false, false
    for p := 2; p * p < 2000000; p++ {
        if v[p] == true {
            for i := p * 2; i < 2000000; i += p {
                v[i] = false
            }
        }
    }
    sum := 0
    for i := 0; i < 2000000; i++ {
        if v[i] == true { sum += i }
    }
    return fmt.Sprintf("%d", sum)
}

func problem11() string {
    return "onzin"
}

/*
#12 Highly divisible triangular number

The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The
first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

Antwoord: 76,576,500
*/

func num_divisors(n int) int {
    if n % 2 == 0 { n = n >> 1 }
    var divisors, count = 1, 0
    for n % 2 == 0 {
        count++
        n = n >> 1
    }
    divisors = divisors * (count + 1)
    var p = 3
    for n != 1 {
        count = 0
        for n % p == 0 {
            count++
            n = n / p
        }
        divisors = divisors * (count + 1)
        p += 2
    }
    return divisors
}

func find_triangular_index(factor_limit int) int {
    var n = 1
    var lnum = num_divisors(n)
    var rnum = num_divisors(n + 1)
    for lnum * rnum < factor_limit {
        lnum = rnum
        n += 1
        rnum = num_divisors(n + 1)
    }
    return n
}

func problem12() string {
    var i = find_triangular_index(500)
    return fmt.Sprintf("%d", (i * (i + 1)) >> 1)
}

/*
#13 Large sum

Work out the first ten digits of the sum of the following one-hundred 50-digit numbers.

Antwoord: 5,537,376,230
*/

func problem13() string {
    return "onzin"
}



/*
#14 Longest Collatz sequence

The following iterative sequence is defined for the set of positive integers:

n -> n/2 (n is even)
n -> 3n + 1 (n is odd)

Using the rule above and starting with 13, we generate the following sequence:
13 -> 40 -> 20 -> 10 -> 5 -> 16 -> 8 -> 4 -> 2 -> 1

It can be seen that this sequence (starting at 13 and finishing at 1)
contains 10 terms. Although it has not been proved yet (Collatz Problem),
it is thought that all starting numbers finish at 1.

Which starting number, under one million, produces the longest chain?

NOTE: Once the chain starts the terms are allowed to go above one million.

Antwoord: 837,799
*/

func collatz(n int) int {
    var count = 1
    for n > 1 {
        if n % 2 == 0 {
            n = n >> 1
        } else { n = n * 3 + 1 }
        count++
    }
    return count
}

func problem14() string {
    var lower, upper, best_start, best_length = 1, 1000000, 0, 0
    for i := lower; i < upper; i++ {
        var length = collatz(i)
        if length > best_length { best_start, best_length = i, length }
    }
    return fmt.Sprintf("%d", best_start)
}

/*
#15 Lattice paths

Starting in the top left corner of a 2x2 grid, and only being able to move
to the right and down, there are exactly 6 routes to the bottom right corner.

How many such routes are there through a 20x20 grid?

Antwoord: 137,846,528,820
*/

func problem15() string {
    var size, paths = 20, 1
    for i := 0; i < size; i++ {
        paths = (paths * (2 * size - i)) / (i + 1)
    }
    return fmt.Sprintf("%d", paths)
}

func problem16() string {
    return "onzin"
}

/*
#26: Reciprocal cycles

A unit fraction contains 1 in the numerator. The decimal representation
of the unit fractions with denominators 2 to 10 are given:

    1/2 =  0.5
    1/3 =  0.(3)
    1/4 =  0.25
    1/5 =  0.2
    1/6 =  0.1(6)
    1/7 =  0.(142857)
    1/8 =  0.125
    1/9 =  0.(1)
    1/10 =  0.1 

Where 0.1(6) means 0.166666..., and has a 1-digit recurring
cycle. It can be seen that 1/7 has a 6-digit recurring cycle.

Find the value of d < 1000 for which 1/d contains the
longest recurring cycle in its decimal fraction part.

Antwoord: 983
*/

/*
Simpel algoritme om cycle length te bepalen, werkt niet
voor sommige nummers met cycle length 1, dan wordt er
0 teruggegeven. Dit zal de uitkomst van deze opdracht niet veranderen
*/

func cycleLength(n int) int {
    var a, t = 1, 0
    for t < n {
        a = a * 10 % n
        t++
        if a == 0 { return 0 }
        if a == 1 { return t }
    }
    return 0
}

func problem26() string {
    var best_n, best_length = 0, 0
    for i := 999; i > 1; i-- {
        var clength = cycleLength(i)
        if clength > best_length {
            best_n, best_length = i, clength
            if best_length == i - 1 { break }
        }
    }
    return fmt.Sprintf("%d", best_n)
}

/*
#27: Quadratic primes

Euler discovered the remarkable quadratic formula:

n^2 + n + 41

It turns out that the formula will produce 40 primes for the consecutive
integer values 0 <= n <= 39. However, when n = 40, 40^2 + 40 + 41 = 40(40 + 1) + 41 is
divisible by 41, and certainly when n = 41, 41^2 + 41 + 41 is clearly divisible by 41.

The incredible formula n^2 - 79n + 1601 was discovered, which produces 80
primes for the consecutive values 0 <= n <= 79. The product of the
coefficients, −79 and 1601, is −126479.

Considering quadratics of the form:

n^2 + an + b, where |a| < 1000 and |b| <= 1000

where |n| is the modulus/absolute value of n
e.g. |11| = 11 and |−4| = 4

Find the product of the coefficients, a and b, for the quadratic expression
that produces the maximum number of primes for consecutive values of n,
starting with n = 0.

Antwoord: -59231
*/

/*
#28 Number spiral diagonals

Starting with the number 1 and moving to the right in a
clockwise direction a 5 by 5 spiral is formed as follows:

21 22 23 24 25
20  7  8  9 10
19  6  1  2 11
18  5  4  3 12
17 16 15 14 13

It can be verified that the sum of the numbers on the diagonals is 101.

What is the sum of the numbers on the diagonals
in a 1001 by 1001 spiral formed in the same way?

Antwoord: 669,171,001
*/

func problem28() string {
    var xsum, step, foo, root int32 = 1, 2, 1, 1001
    for foo < root * root {
        for i := int32(0); i < 4; i++ {
            foo += step
            xsum += foo
        }
        step += 2
    }
    return fmt.Sprintf("%d", xsum)
}

func run2(p uint32) string {
    switch p {
    case 1:
        return problem1()
    case 2:
        return problem2()
    case 3:
        return problem3()
    case 4:
        return problem4()
    case 5:
        return problem5()
    case 6:
        return problem6()
    case 7:
        return problem7()
    case 8:
        return "onzin"
    case 9:
        return problem9()
    case 10:
        return problem10()
    case 11:
        return problem11()
    case 12:
        return problem12()
    case 13:
        return problem13()
    case 14:
        return problem14()
    case 15:
        return problem15()
    case 16:
        return problem16()
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
        return "onzin"
    case 26:
        return problem26()
    case 28:
        return problem28()
    }
    return "onzin"
}

func main() {
    for i := uint32(1); i <= 28; i++ {
        fmt.Printf("Oplossing %d: %s\n", i, run2(i))
    }
}



